name: Node App Helper Actions

on:
  push:
  schedule:
    - cron: '0 0,10 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run start
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.COMMIT_SECRET }}
        publish_dir: ./
        publish_branch: gh-pages
        force_orphan: true
        keep_files: true
