name: Node App Helper Actions

on:
  push:
  schedule:
    - cron: '0 0,10 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn install
    - run: yarn start
    - run: mkdir public
    - run: cp ./stock-public-form.xml ./public/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./public
        publish_branch: gh-pages
        allow_empty_commit: false
        keep_files: true
        force_orphan: true
